name: Testing GitHub-Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create Comment
        id: create-comment
        uses: actions/github-script@v5
        with:
          node-version: '20'
          script: |
            const issue_number = 1; // Replace with the actual issue number
            const { owner, repo } = context.repo;

            const response = await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: "I created this comment using the github-script action!"
            });

            return response.data; // Return the response data
      - name: Get result
        run: echo "${{ steps.create-comment.outputs.result }}"
